<?php

declare(strict_types=1);
$lock = fopen(__FILE__, 'rb');
if (!flock($lock, LOCK_EX | LOCK_NB)) {
    die("Already running.\n");
}
/**
 * better version of shell_exec(),
 * supporting both stdin and stdout and stderr and os-level return code
 *
 * @param string $cmd
 *            command to execute
 * @param string $stdin
 *            (optional) data to send to stdin, binary data is supported.
 * @param string $stdout
 *            (optional) stdout data generated by cmd
 * @param string $stderr
 *            (optional) stderr data generated by cmd
 * @param bool $print_std
 *            (optional, default false) if you want stdout+stderr to be printed while it's running,
 *            set this to true. (useful for long-running commands)
 * @return int
 */
function hhb_exec(string $cmd, string $stdin = "", string &$stdout = null, string &$stderr = null, bool $print_std = false): int
{
    $stdouth = tmpfile();
    $stderrh = tmpfile();
    $descriptorspec = array(
        0 => array(
            "pipe",
            "rb"
        ), // stdin
        1 => array(
            "file",
            stream_get_meta_data($stdouth)['uri'],
            'ab'
        ),
        2 => array(
            "file",
            stream_get_meta_data($stderrh)['uri'],
            'ab'
        )
    );
    $pipes = array();
    $proc = proc_open($cmd, $descriptorspec, $pipes);
    while (strlen($stdin) > 0) {
        $written_now = fwrite($pipes[0], $stdin);
        if ($written_now < 1 || $written_now === strlen($stdin)) {
            // ... can add more error checking here
            break;
        }
        $stdin = substr($stdin, $written_now);
    }
    fclose($pipes[0]);
    unset($stdin, $pipes[0]);
    if (!$print_std) {
        $proc_ret = proc_close($proc); // this line will stall until the process has exited.
        $stdout = stream_get_contents($stdouth);
        $stderr = stream_get_contents($stderrh);
    } else {
        $stdout = "";
        $stderr = "";
        stream_set_blocking($stdouth, false);
        stream_set_blocking($stderrh, false);
        $fetchstd = function () use (&$stdout, &$stderr, &$stdouth, &$stderrh): bool {
            $ret = false;
            $tmp =  stream_get_contents($stdouth); // fread($stdouth, 1); //
            if (is_string($tmp) && strlen($tmp) > 0) {
                $ret = true;
                $stdout .= $tmp;
                fwrite(STDOUT, $tmp);
            }
            $tmp = stream_get_contents($stderrh); // fread($stderrh, 1); //
            // var_dump($tmp);
            if (is_string($tmp) && strlen($tmp) > 0) {
                $ret = true;
                $stderr .= $tmp;
                fwrite(STDERR, $tmp);
            }
            return $ret;
        };
        while (($status = proc_get_status($proc))["running"]) {
            if (!$fetchstd()) {
                // 100 ms
                usleep(100 * 1000);
            }
        }
        $proc_ret = $status["exitcode"];
        proc_close($proc);
        $fetchstd();
    }
    fclose($stdouth);
    fclose($stderrh);
    return $proc_ret;
}

$cmd = "php index.php 2>&1";
for (;;) {
    echo ".";
    $ret = hhb_exec($cmd, "", $stdout, $stderr, true);
    $expected = array(
        'ret' => 0,
        'stdout' => '{
          "code": "InternalError",
          "message": "Out of host capacity."
      }
      {
          "code": "InternalError",
          "message": "Out of host capacity."
      }
      {
          "code": "InternalError",
          "message": "Out of host capacity."
      }
      ',
        'stderr' => '',
    );
    $expected['stdout'] = trim($expected['stdout']);
    $actual = array(
        'ret' => $ret,
        'stdout' => $stdout,
        'stderr' => $stderr,
    );
    $actual['stdout'] = trim($actual['stdout']);
    if (
        str_starts_with($actual['stdout'], 'PHP Fatal error:  Uncaught Hitrov\\Exception\\TooManyRequestsWaiterException: Will retry after')
        || str_contains($actual['stdout'], '"TooManyRequests"')
    ) {
        // Will retry after 83 seconds
        preg_match('/Will retry after (\d+) seconds/', $actual['stdout'], $matches);
        //var_dump($matches);
        $seconds = (int) ($matches[1] ?? 100);
        $seconds = 1000;
        for ($i = 1; $i < ($seconds + 1); ++$i) {
            echo "{$i}/{$seconds}\r";
            sleep(1);
        }
        echo "\n";
        continue;
    }
    if (
        preg_replace('/\s+/', '', $expected['stdout']) !== preg_replace('/\s+/', '', $actual['stdout'])
    ) {
        echo "Unexpected STDOUT output, dumping...\n";
        $actual = var_export($actual, true);
        $expected = var_export($expected, true);
        file_put_contents(__FILE__ . ".actual", $actual);
        file_put_contents(__FILE__ . ".expected", $expected);
        echo "Actual output:\n$actual\n";
        die();
    }
    if ($expected['stderr'] !== $actual['stderr']) {
        echo "Unexpected STDERR output, dumping...\n";
        $actual = var_export($actual, true);
        $expected = var_export($expected, true);
        file_put_contents(__FILE__ . ".actual", $actual);
        file_put_contents(__FILE__ . ".expected", $expected);
        echo "Actual output:\n$actual\n";
        die();
    }
    if ($expected['ret'] !== $actual['ret']) {
        echo "Unexpected return code, dumping...\n";
        $actual = var_export($actual, true);
        $expected = var_export($expected, true);
        file_put_contents(__FILE__ . ".actual", $actual);
        file_put_contents(__FILE__ . ".expected", $expected);
        echo "Actual output:\n$actual\n";
        die();
    }
    for($i=1,$imax=701;$i<$imax; ++$i){
        echo "{$i}/{$imax}\r";
        sleep(1);
    }
    continue;
    echo "Unexpected output, dumping...\n";
    $actual = var_export($actual, true);
    $expected = var_export($expected, true);
    file_put_contents(__FILE__ . ".actual", $actual);
    file_put_contents(__FILE__ . ".expected", $expected);
    echo "Actual output:\n$actual\n";
    die();
}
