<?php

declare(strict_types=1);
$lock = fopen(__FILE__, 'rb');
if (!flock($lock, LOCK_EX | LOCK_NB)) {
    die("Already running.\n");
}
/**
 * better version of shell_exec(),
 * supporting both stdin and stdout and stderr and os-level return code
 *
 * @param string $cmd
 *            command to execute
 * @param string $stdin
 *            (optional) data to send to stdin, binary data is supported.
 * @param string $stdout
 *            (optional) stdout data generated by cmd
 * @param string $stderr
 *            (optional) stderr data generated by cmd
 * @param bool $print_std
 *            (optional, default false) if you want stdout+stderr to be printed while it's running,
 *            set this to true. (useful for long-running commands)
 * @return int
 */
function hhb_exec(string $cmd, string $stdin = "", string &$stdout = null, string &$stderr = null, bool $print_std = false): int
{
    $stdouth = tmpfile();
    $stderrh = tmpfile();
    $descriptorspec = array(
        0 => array(
            "pipe",
            "rb"
        ), // stdin
        1 => array(
            "file",
            stream_get_meta_data($stdouth)['uri'],
            'ab'
        ),
        2 => array(
            "file",
            stream_get_meta_data($stderrh)['uri'],
            'ab'
        )
    );
    $pipes = array();
    $proc = proc_open($cmd, $descriptorspec, $pipes);
    while (strlen($stdin) > 0) {
        $written_now = fwrite($pipes[0], $stdin);
        if ($written_now < 1 || $written_now === strlen($stdin)) {
            // ... can add more error checking here
            break;
        }
        $stdin = substr($stdin, $written_now);
    }
    fclose($pipes[0]);
    unset($stdin, $pipes[0]);
    if (!$print_std) {
        $proc_ret = proc_close($proc); // this line will stall until the process has exited.
        $stdout = stream_get_contents($stdouth);
        $stderr = stream_get_contents($stderrh);
    } else {
        $stdout = "";
        $stderr = "";
        stream_set_blocking($stdouth, false);
        stream_set_blocking($stderrh, false);
        $fetchstd = function () use (&$stdout, &$stderr, &$stdouth, &$stderrh): bool {
            $ret = false;
            $tmp =  stream_get_contents($stdouth); // fread($stdouth, 1); //
            if (is_string($tmp) && strlen($tmp) > 0) {
                $ret = true;
                $stdout .= $tmp;
                fwrite(STDOUT, $tmp);
            }
            $tmp = stream_get_contents($stderrh); // fread($stderrh, 1); //
            // var_dump($tmp);
            if (is_string($tmp) && strlen($tmp) > 0) {
                $ret = true;
                $stderr .= $tmp;
                fwrite(STDERR, $tmp);
            }
            return $ret;
        };
        while (($status = proc_get_status($proc))["running"]) {
            if (!$fetchstd()) {
                // 100 ms
                usleep(100 * 1000);
            }
        }
        $proc_ret = $status["exitcode"];
        proc_close($proc);
        $fetchstd();
    }
    fclose($stdouth);
    fclose($stderrh);
    return $proc_ret;
}

$cmd = "php index.php --debug 2>&1";

for (;;) {
    echo "Attempting to acquire ARM slot in Mumbai...\n";
    $ret = hhb_exec($cmd, "", $stdout, $stderr, true);
    
    $actual_output = trim($stdout);

    // 1. Check for Success (If the output DOES NOT contain "InternalError" or "TooManyRequests")
    if ($ret === 0 && str_contains($actual_output, '"id": "ocid1.instance')) {
        echo "\n!!! VICTORY !!! Instance Created successfully.\n";
        exit(0); // This stops the GitHub Action with a GREEN checkmark
    }

    // 2. Handle Capacity Error (This is what you are seeing now)
    if (str_contains($actual_output, 'Out of host capacity.')) {
        echo " [Status] Mumbai is full. Waiting 60 seconds before retrying...\n";
        sleep(60); 
        continue; // Restarts the loop
    }

    // 3. Handle Rate Limiting (Too Many Requests)
    if (str_contains($actual_output, 'TooManyRequests') || str_contains($actual_output, 'Will retry after')) {
        preg_match('/Will retry after (\d+) seconds/', $actual_output, $matches);
        $wait = (int)($matches[1] ?? 120);
        echo " [Throttle] Oracle is rate-limiting us. Waiting {$wait} seconds...\n";
        sleep($wait);
        continue;
    }

    // 4. Handle Real Errors (If something is actually broken)
    echo "Unexpected Output Received. Dumping for debug:\n";
    echo $actual_output;
    die("\nScript stopped to prevent infinite error loop.\n");
}
